# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-hooks.json
-   &base
    id: opa-fmt
    name: opa fmt
    args:
    - fmt
    - --write
    language: golang
    entry: opa
    files: \.rego$
    additional_dependencies:
    - github.com/open-policy-agent/opa@latest

-   <<: *base
    id: opa-check
    args:
    - check
